export const colors = {
	PRIMARY_COLOR: "#344955",
	PRIMARY_COLOR_DARK: "#0B222C",
	PRIMARY_COLOR_LIGHT: "#5f7481",
	PRIMARY_COLOR_TEXT: "#ffffff",
	SECONDARY_COLOR: "#F9AA33",
	SECONDARY_COLOR_LIGHT: "#ffdc65",
	SECONDARY_COLOR_DARK: "#c17b00",
	SECONDARY_COLOR_TEXT: "#000000",
};

export const fonts = {
	FONT_SIZE_SMALL: 12,
	FONT_SIZE_MEDIUM: 14,
	FONT_SIZE_LARGE: 16,
	FONT_WEIGHT_LIGHT: 200,
	FONT_WEIGHT_MEDIUM: 600,
	FONT_WEIGHT_HEAVY: 800,
};
